grid_map_topic: /grid_map
grid_map_visualizations:
  - name: cost_map
    type: occupancy_grid
    params:
     layer: cost_map
     data_min: 0.0
     data_max: 0.5
  - name: occgrid_map
    type: occupancy_grid
    params:
     layer: occgrid_map
     data_min: 0.0
     data_max: 0.5
